require(['jquery','core/ajax'],function($,ajax){var getPageLayout=function(){var classes=$('body').attr('class').split(' ');var result='base';$(classes).each(function(index,value){if(value.indexOf("pagelayout-")!==-1){var layout=value.split('-');return result=layout[1]}});return result};$('.collapsible-section-switcher-slideup-label').click(function(){var switcher=$(this).parent().children('.collapsible-section-switcher').attr('checked','checked');var collapsibleSectionTop=$(this).parent().offset().top;if($(document).scrollTop()>collapsibleSectionTop){$('html, body').animate({scrollTop:collapsibleSectionTop},400)}
$(this).parent().children('.collapsible-section-switcher-slideup-label').first().slideUp();$(this).parent().children('.collapsible-section-content').slideUp(function(){$(this).parent().removeClass('expanded').addClass('collapsed');switcher.trigger('click').removeAttr('checked');save_cs_state(switcher.parent().data('collapsible-section'),0)})});$('.collapsible-section-switcher-slidedown-label').click(function(){var switcher=$(this).parent().children('.collapsible-section-switcher').removeAttr('checked');$(this).parent().children('.collapsible-section-switcher-slideup-label').first().slideDown();$(this).parent().children('.collapsible-section-content').slideDown(function(){$(this).parent().removeClass('collapsed').addClass('expanded');switcher.trigger('click').attr('checked','checked');save_cs_state(switcher.parent().data('collapsible-section'),1)})});var save_cs_state=function(collapsiblesection,currentstate){var layout=getPageLayout();var requests=ajax.call([{methodname:'theme_opentechnology_set_collapsiblesection_state',args:{'collapsiblesection':collapsiblesection,'state':currentstate,'layout':layout}}])}});require(['jquery'],function($){var slides=$('.loginpage_slider_images > .loginpage_slider_image');var currentslideindex=0;if(slides.length>1){setInterval(function(){slidefrom=slides[currentslideindex];if(slides.length==++currentslideindex){currentslideindex=0}
slideto=slides[currentslideindex];slidefrom.style.opacity="0";slideto.style.opacity="1"},5000)}});require(['jquery'],function($){var fixElement=function(overflowedElementSelector,sourceElementSelector,cloneElementSelector,fixLeft,fixTop){if(overflowedElementSelector==undefined){overflowedElementSelector=null}
if(sourceElementSelector==undefined){sourceElementSelector=null}
if(cloneElementSelector==undefined){cloneElementSelector=null}
if(fixLeft==undefined){fixLeft=!1}
if(fixTop==undefined){fixTop=!0}
var overflowedElement=$(overflowedElementSelector);var sourceElement=$(sourceElementSelector);var cloneElement=$(cloneElementSelector);if(overflowedElement.length==0||sourceElement.length==0||cloneElement.length==0){return}
var scrollTop=overflowedElement.scrollTop();var scrollLeft=overflowedElement.scrollLeft();var sourcePosition=sourceElement.position();var sourcePositionTop=(sourcePosition.top-scrollTop);var sourcePositionLeft=(sourcePosition.left-scrollLeft);var fixedTopPosition=(sourcePositionTop<0?0:sourcePositionTop);var fixedLeftPosition=(sourcePositionLeft<0?0:sourcePositionLeft);if(fixLeft&&cloneElement.width()>overflowedElement.width()/2){fixLeft=!1}
if(fixTop&&cloneElement.height()>overflowedElement.height()/2){fixTop=!1}
if(fixLeft&&(sourceElement.width()+sourcePositionLeft)<cloneElement.children('div:first').width()){cloneElement.addClass('otfloating')}else if(fixTop&&sourcePositionTop<0){cloneElement.addClass('otfloating')}else{cloneElement.removeClass('otfloating')}
cloneElement.css({'left':(fixLeft?fixedLeftPosition:sourcePositionLeft)+scrollLeft+'px','top':(fixTop?fixedTopPosition:sourcePositionTop)+scrollTop+'px'})}
$('body.path-grade-report-grader .gradeparent').scroll(function(){$('body.path-grade-report-grader .floater').each(function(){$(this).clone().removeClass('floater').removeClass('floating').addClass('otfloater').appendTo('.gradeparent')}).remove();fixElement($(this),'body.path-grade-report-grader #user-grades th.header.cell.user:first','body.path-grade-report-grader .otfloater.sideonly:not(.avg):not(.heading):not(.controls)',!0,!1);var shw=$('body.path-grade-report-grader #user-grades th.header.cell.user:first-child');var shh=$('body.path-grade-report-grader #user-grades th.header.cell#studentheader');$('body.path-grade-report-grader .otfloater.sideonly.heading').css({'width':shw.outerWidth()+'px','height':shh.outerHeight()+'px'});fixElement($(this),'body.path-grade-report-grader #user-grades th.header.cell#studentheader','body.path-grade-report-grader .otfloater.sideonly.heading',!0,!0);fixElement($(this),'body.path-grade-report-grader #user-grades th.header.cell.range','body.path-grade-report-grader .otfloater.sideonly.avg',!0,!0);fixElement($(this),'body.path-grade-report-grader #user-grades tr.heading','body.path-grade-report-grader .otfloater.heading:not(.sideonly)',!1,!0);fixElement($(this),'body.path-grade-report-grader #user-grades td.header.cell.controls','body.path-grade-report-grader .otfloater.sideonly.controls',!0,!1)})});var otsearchable;require(['jquery','jqueryui'],function($){otsearchable=function(){$('table.ot-searchable').each(function(){var table=$(this);var config=table.data('searchable-cells');var container=$('<div>').addClass('ot-filter-wrapper');var switcher=$('<input>').attr('type','checkbox').uniqueId().addClass('ot-filter-display');$('<label>').attr('for',switcher.attr('id')).addClass('ot-filter-header').text('Фильтрация').appendTo(container);switcher.appendTo(container);var hide=table.data('searchable-filter-hide');if(hide===undefined||!hide){switcher.attr('checked','checked')}
var filters=$('<div>').addClass('ot-filter-filters').appendTo(container);for(var cellclass in config){var filtertitle=config[cellclass];$('<input>').attr('placeholder',filtertitle).data('ot-filter-cellclass',cellclass).keyup(function(){var searchval=$(this).val();var cellclass=$(this).data('ot-filter-cellclass');var filteredcells=table.find('td.'+cellclass);filteredcells.each(function(index){var row=$(this).closest('tr');if($(this).text().toLowerCase().indexOf(searchval.toLowerCase())!==-1||searchval==''){var hiders=[];if(row.data('ot-filter')!==undefined){var hiders=row.data('ot-filter');var hiderkey=hiders.indexOf(cellclass);if(hiderkey!==-1){hiders.splice(hiderkey,1)}
row.data('ot-filter',hiders)}
if(hiders.length==0){row.removeClass('ot-filter-discard')}}else{row.addClass('ot-filter-discard');if(row.data('ot-filter')===undefined){row.data('ot-filter',[cellclass])}else{var hiders=row.data('ot-filter');if(hiders.indexOf(cellclass)==-1){hiders.push(cellclass);row.data('ot-filter',hiders)}}}})}).appendTo(filters)}
var parent=table.data('searchable-filter-parent');if(parent!==undefined){container.appendTo($(parent).first())}else{container.insertBefore(table)}})};otsearchable()});var otsortable;require(['jquery'],function($){var ot_sort_table=function(table,cellclass,desc){if(typeof desc=='undefined'){desc=!1}
var rejected=[];var suitable=[];var header=[];table.find('tr').each(function(index){if($(this).hasClass('ot-sort-fix-top')){header.push($(this));return!0}
var suitable_cells=$(this).find('td.'+cellclass);if(suitable_cells.length>0){var suitable_cell=suitable_cells.first();var sortablevalue=suitable_cell.data('sort-value');if(sortablevalue===undefined){sortablevalue=suitable_cell.text()}
suitable[(''+sortablevalue).toLowerCase()+index]=$(this)}else{rejected.push($(this))}});if(!desc){for(var key in header){table.append(header[key])}
Object.keys(suitable).sort().forEach(function(key){table.append(suitable[key])});for(var key in rejected){table.append(rejected[key])}}else{for(var key=(rejected.length-1);key>=0;key--){table.prepend(rejected[key])}
Object.keys(suitable).sort().forEach(function(key){table.prepend(suitable[key])});for(var key=(header.length-1);key>=0;key--){table.prepend(header[key])}}}
otsortable=function(){$('table.ot-sortable').each(function(){var table=$(this);var config=table.data('sortable-cells');for(var headercellclass in config){var datacellclass=config[headercellclass];table.find('th.'+headercellclass).each(function(){var tools=$('<div>').addClass('ot-sort-tools');$('<div>').addClass('ot-sort-tool-sortup').click(function(){ot_sort_table(table,datacellclass,!0)}).appendTo(tools);$('<div>').addClass('ot-sort-tool-sortdown').click(function(){ot_sort_table(table,datacellclass)}).appendTo(tools);$(this).data('ot-sort-cellclass',datacellclass).append(tools)})}})};otsortable()})